const baseUrl_1 = "https://stage-pilot-train-booking-system.onrender.com";

final popular_title = ['Galle', 'Badulla', 'Kandy'];
final popular_content = [
  'Both these cities are located at a distance of 113.89 kms. Traveling from one place to the other is easy because of the efficient rail connectivity. There are many trains that run between the two cities. On a daily basis, There are 69 weekly trains from Colombo Fort to Galle.',
  "Badulla railway station (බදුල්ල දුම්රිය ස්ථානය) is the last station on the Main Line, and is 292.3 km (181.6 mi) away from Colombo. It is located 652.43 m (2,140.5 ft) above mean sea level and 1 km (0.62 mi) from Badulla, the capital city of Uva Province. The trains that run on the Main Line, including the Podi Menike and Udarata Menike express trains end at the station..",
  "Kandy is both an administrative and religious city and is also the capital of the Central Province. Kandy is the home of the Temple of the Tooth Relic (Sri Dalada Maligawa), one of the most sacred places of worship in the Buddhist world. It was declared a World Heritage Site by UNESCO in 1988."
];

List<String> Staions = [
  "Ahangama",
  "Aluthgama",
  "Ambalangoda",
  "Ambalangoda",
  "Ambewela",
  "Anuradhapura",
  "Anuradhapura Town",
  "Avissawella",
  "Badulla",
  "Bandarawela",
  "Batticaloa",
  "Beliaththa",
  "Bentota",
  "Beruwala",
  "China bay",
  "Chunnakam",
  "Colombo Fort",
  "Demodara-Ella",
  "Diyathalawa",
  "Ella",
  "Eraur",
  "Galgamuwa",
  "Galle",
  "Galoya",
  "Gampaha",
  "Gampola",
  "Habaraduwa",
  "Habarana",
  "Hali Ela",
  "Haputhale",
  "Hatton",
  "Hikkaduwa",
  "Hingurakgoda",
  "Jaffna",
  "Kakirawa",
  "Kalutara South",
  "Kamburugamuwa",
  "Kandy",
  "Kankesanthurai",
  "Kanthale",
  "Kilinochchi",
  "Kodikamam",
  "Koggala",
  "Kurunegala",
  "Madhupara",
  "Mahawa",
  "Makumbura",
  "Mannar",
  "Maradhana",
  "Matale",
  "Matara",
  "Medawachchiya",
  "Mirigama",
  "Mirissa",
  "Moratuwa",
  "Mount Lavinia",
  "NAGOLLAGAMA",
  "Nanu Oya",
  "Nawalapitiya",
  "Nawalapitya",
  "Nugegoda",
  "Omantha",
  "Pallai",
  "Panadura",
  "Peradeniya",
  "Polgahawela",
  "Polonnaruwa",
  "Puwakpitiya",
  "Ragama",
  "Rambukkana",
  "Rathmalana",
  "Return Colombo",
  "Return Waga",
  "Talaimannar Pier",
  "Thambalagamuwa",
  "Thambuththegama",
  "Thandikulam",
  "Trincomalee",
  "Unawatuna",
  "Valachchena",
  "Vauniya",
  "Veyangoda",
  "Veyangoda",
  "Waduwwa",
  "Weligama",
  "Welikanda",
  "Wellawa",
  "Wellawatte"
];
